name: Deploy to Server

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: git pull origin production
        working-directory: D:\backend\mcs_backend

      - name: Deploy with Docker
        run: docker compose up -d --build
        working-directory: D:\backend\mcs_backend
